insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (1, 'Domesticated red fox (Vulpes vulpes)', 'Rose Elliott', 'http://dummyimage.com/132x177.bmp/ff4444/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (2, 'Yak (Bos grunniens)', 'Raymond Smith', 'http://dummyimage.com/149x202.bmp/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (3, 'Cochineal (Dactylopius coccus)', 'Diane Henry', 'http://dummyimage.com/216x188.bmp/dddddd/000000', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (4, 'Leopard gecko (Eublepharis macularius)', 'Edward Roberts', 'http://dummyimage.com/210x138.png/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (5, 'Salmon-crested cockatoo (Cacatua moluccensis)', 'Dennis Nguyen', 'http://dummyimage.com/231x153.jpg/ff4444/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (6, 'European mink (Mustela lutreola)', 'Kevin Gonzales', 'http://dummyimage.com/193x155.jpg/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (7, 'Green and black poison dart frog (Dendrobates auratus)', 'Donald Riley', 'http://dummyimage.com/195x119.bmp/cc0000/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (8, 'Lowland paca (Cuniculus paca)', 'Shawn Riley', 'http://dummyimage.com/118x216.png/dddddd/000000', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (9, 'Star finch (Neochmia ruficauda)', 'Albert Rogers', 'http://dummyimage.com/205x205.jpg/ff4444/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (10, 'Greater rhea (Rhea americana)', 'Kenneth Grant', 'http://dummyimage.com/217x166.png/5fa2dd/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (11, 'Tarantula (Brachypelma spp. et al.)', 'Jeffrey Grant', 'http://dummyimage.com/189x132.jpg/dddddd/000000', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (12, 'Semi-domesticated reindeer (Rangifer tarandus)', 'Nicole Lee', 'http://dummyimage.com/221x191.jpg/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (13, 'Piranha (Pygocentrus nattereri et al.)', 'Jeffrey Austin', 'http://dummyimage.com/149x249.jpg/cc0000/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (14, 'Domestic pig (Sus scrofa domesticus)', 'Annie Lawson', 'http://dummyimage.com/132x119.png/5fa2dd/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (15, 'Gouldian finch (Erythrura gouldiae)', 'Patricia Palmer', 'http://dummyimage.com/143x212.png/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (16, 'Common hill myna (Gracula religiosa)', 'Jose Hayes', 'http://dummyimage.com/225x167.jpg/cc0000/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (17, 'Major Mitchell''s cockatoo (Lophochroa leadbeateri)', 'Paul Rogers', 'http://dummyimage.com/226x171.bmp/5fa2dd/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (18, 'Pekin robin (Leiothrix lutea)', 'Jean Murray', 'http://dummyimage.com/139x245.jpg/dddddd/000000', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (19, 'American mink (Neovison vison)', 'Christine Brown', 'http://dummyimage.com/168x196.png/5fa2dd/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (20, 'Alligator (Alligator mississippiensis)', 'David Brooks', 'http://dummyimage.com/160x138.png/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (21, 'Semi-domesticated reindeer (Rangifer tarandus)', 'Marilyn Simmons', 'http://dummyimage.com/109x102.jpg/dddddd/000000', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (22, 'Domestic muscovy duck (Cairina moschata domestica)', 'Denise Carr', 'http://dummyimage.com/145x144.bmp/dddddd/000000', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (23, 'Degu (Octodon degus)', 'Lillian Stephens', 'http://dummyimage.com/120x111.jpg/5fa2dd/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (24, 'Red deer (Cervus elaphus)', 'Henry King', 'http://dummyimage.com/192x236.png/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (25, 'Cockatiel (Nymphicus hollandicus)', 'Doris Butler', 'http://dummyimage.com/132x102.png/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (26, 'Ringneck dove (Streptopelia risoria)', 'Craig Gonzalez', 'http://dummyimage.com/196x200.png/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (27, 'Cat (Felis silvestris catus)', 'Diane Welch', 'http://dummyimage.com/132x104.bmp/ff4444/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (28, 'Roman snail (Helix pomatia)', 'Michael Woods', 'http://dummyimage.com/189x140.bmp/cc0000/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (29, 'Ferret (Mustela putorius furo)', 'Katherine Shaw', 'http://dummyimage.com/179x125.bmp/ff4444/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (30, 'Red-tailed black cockatoo (Calyptorhynchus banksii)', 'Kathryn Ross', 'http://dummyimage.com/184x173.png/ff4444/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (31, 'Sulphur-crested cockatoo (Cacatua galerita)', 'Virginia Harvey', 'http://dummyimage.com/177x175.jpg/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (32, 'Kissing gourami (Helostoma temminckii)', 'Betty Hanson', 'http://dummyimage.com/133x155.jpg/dddddd/000000', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (33, 'White cockatoo (Cacatua alba)', 'George Crawford', 'http://dummyimage.com/189x231.png/dddddd/000000', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (34, 'Kissing gourami (Helostoma temminckii)', 'Martin Wagner', 'http://dummyimage.com/156x207.png/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (35, 'European medicinal leech (Hirudo medicinalis)', 'Carl Cunningham', 'http://dummyimage.com/177x187.png/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (36, 'Palm cockatoo (Probosciger aterrimus)', 'Wanda Warren', 'http://dummyimage.com/176x186.jpg/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (37, 'European goldfinch (Carduelis carduelis)', 'Rebecca Gomez', 'http://dummyimage.com/160x157.bmp/ff4444/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (38, 'European mink (Mustela lutreola)', 'Joan Day', 'http://dummyimage.com/238x250.jpg/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (39, 'Dog (Canis lupus familiaris)', 'John Perry', 'http://dummyimage.com/146x107.jpg/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (40, 'Axolotl (Ambystoma mexicanum)', 'Karen Simpson', 'http://dummyimage.com/106x155.jpg/dddddd/000000', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (41, 'Elk (Cervus canadensis)', 'Willie Scott', 'http://dummyimage.com/190x147.jpg/5fa2dd/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (42, 'Japanese quail (Coturnix japonica)', 'Frances Lee', 'http://dummyimage.com/244x231.jpg/dddddd/000000', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (43, 'White cockatoo (Cacatua alba)', 'Larry Gordon', 'http://dummyimage.com/102x198.jpg/5fa2dd/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (44, 'Leopard gecko (Eublepharis macularius)', 'Debra Cook', 'http://dummyimage.com/149x215.bmp/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (45, 'Fancy rat and Lab rat', 'Jerry Oliver', 'http://dummyimage.com/175x105.png/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (46, 'Fancy mouse', 'Jennifer Burton', 'http://dummyimage.com/151x171.bmp/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (47, 'European mink (Mustela lutreola)', 'Debra Wagner', 'http://dummyimage.com/235x226.bmp/dddddd/000000', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (48, 'Eclectus parrot (Eclectus roratus)', 'Denise Russell', 'http://dummyimage.com/117x217.png/ff4444/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (49, 'Palm cockatoo (Probosciger aterrimus)', 'Tina Rogers', 'http://dummyimage.com/241x228.bmp/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (50, 'Pekin robin (Leiothrix lutea)', 'Anne Kim', 'http://dummyimage.com/187x102.jpg/5fa2dd/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (51, 'Indian gray mongoose (Herpestes edwardsii)', 'Nicholas Holmes', 'http://dummyimage.com/218x177.bmp/dddddd/000000', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (52, 'Pale and lesser gerbils (Gerbillus perpallidus', 'Gerald Hall', 'http://dummyimage.com/237x234.jpg/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (53, 'Kissing gourami (Helostoma temminckii)', 'Tina Mendoza', 'http://dummyimage.com/204x222.png/5fa2dd/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (54, 'Llama (Lama glama)', 'Douglas Perkins', 'http://dummyimage.com/212x194.jpg/5fa2dd/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (55, 'Red deer (Cervus elaphus)', 'Russell Hansen', 'http://dummyimage.com/104x146.png/cc0000/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (56, 'Domesticated red fox (Vulpes vulpes)', 'Nicholas Gonzalez', 'http://dummyimage.com/180x140.bmp/dddddd/000000', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (57, 'Domestic skunk (Mephitis mephitis)', 'Sandra Thomas', 'http://dummyimage.com/140x117.png/dddddd/000000', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (58, 'Society finch (Lonchura striata domestica)', 'Lois Griffin', 'http://dummyimage.com/113x202.png/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (59, 'Sulphur-crested cockatoo (Cacatua galerita)', 'Ralph Perez', 'http://dummyimage.com/231x137.png/ff4444/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (60, 'Domestic pigeon (Columba livia domestica)', 'Elizabeth Warren', 'http://dummyimage.com/205x240.bmp/dddddd/000000', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (61, 'Indian palm squirrel (Funambulus palmarum)', 'Lisa Russell', 'http://dummyimage.com/138x177.png/5fa2dd/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (62, 'Golden hamster (Mesocricetus auratus)', 'David Harris', 'http://dummyimage.com/173x180.bmp/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (63, 'Crucian carp (Carassius carassius)', 'Patrick Fernandez', 'http://dummyimage.com/185x149.bmp/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (64, 'Moose (Alces alces)', 'Martha Nguyen', 'http://dummyimage.com/202x202.bmp/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (65, 'Black spiny-tailed iguana (Ctenosaura similis)', 'Amanda Reed', 'http://dummyimage.com/196x224.png/5fa2dd/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (66, 'White cockatoo (Cacatua alba)', 'Sean Washington', 'http://dummyimage.com/168x196.jpg/dddddd/000000', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (67, 'Cockatiel (Nymphicus hollandicus)', 'Jeremy Thompson', 'http://dummyimage.com/114x241.bmp/ff4444/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (68, 'Dwarf hamsters (Phodopus spp.)', 'Heather Hernandez', 'http://dummyimage.com/227x193.png/ff4444/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (69, 'Red flour beetle (Tribolium castaneum)', 'Anna Banks', 'http://dummyimage.com/101x105.bmp/ff4444/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (70, 'Domestic muscovy duck (Cairina moschata domestica)', 'Virginia Dean', 'http://dummyimage.com/113x159.png/cc0000/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (71, 'Grey francolin (Francolinus pondicerianus)', 'Jacqueline Lewis', 'http://dummyimage.com/188x155.png/ff4444/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (72, 'Semi-domesticated reindeer (Rangifer tarandus)', 'Laura Cox', 'http://dummyimage.com/227x158.bmp/ff4444/ffffff', 'Pending');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (73, 'Egyptian goose (Alopochen aegyptiacus)', 'Diane Day', 'http://dummyimage.com/167x136.jpg/ff4444/ffffff', 'Available');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (74, 'Fancy rat and Lab rat', 'Justin Peters', 'http://dummyimage.com/215x118.png/cc0000/ffffff', 'Sold');
insert into PET (ID, TYPE, NAME, PHOTO_URL, STATUS) values (75, 'Gayal (Bos frontalis)', 'Rebecca Gardner', 'http://dummyimage.com/162x116.jpg/cc0000/ffffff', 'Sold');